org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=256m -Dfile.encoding=UTF-8
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.caching=true

kotlin.compiler.execution.strategy=in-process

android.useAndroidX=true
android.enableJetifier=false
kotlin.jvm.target.validation.mode=warning

# CI build trigger
