-- Room IDs are generated by the database identity column.
-- Keep the numeric Room ID globally unique and add a secure lookup RPC.

alter table public.rooms
  add constraint rooms_room_number_unique unique (room_number);

create or replace function public.search_room_by_number(p_room_number bigint)
returns table(
  room_id uuid,
  room_number bigint,
  room_name text,
  owner_uid uuid,
  owner_name text,
  profile_url text,
  has_password boolean,
  member_count bigint
)
language sql
security definer
set search_path = public
as $function$
  select
    r.id,
    r.room_number,
    r.name,
    r.owner_uid,
    coalesce(u."userName", 'User'),
    coalesce(r.profile_url, ''),
    (r.password_hash is not null),
    (select count(*) from public.room_entries e where e.room_id = r.id and e.exited_at is null)
  from public.rooms r
  join public.users u on u.uid = r.owner_uid
  where r.room_number = p_room_number
  limit 1
$function$;

revoke all on function public.search_room_by_number(bigint) from public, anon, authenticated;
grant execute on function public.search_room_by_number(bigint) to authenticated;
